
logo: "images/prestashop-logo.svg?v=2025"
logo_width: "200px"

license: Content distributed under the [Creative Commons BY-SA 4.0 License](https://creativecommons.org/licenses/by-sa/4.0/legalcode).
copyright: '"PrestaShop" and the PrestaShop logos are international trademarks of PrestaShop SA.'

variables:
    primary_color: "#000"
    text_color: "#000"
    text_color_dark: "#000"
    body_color: "#fff"
    border_color: "#ECECEC"
    black: "#000"
    white: "#fff"
    light: "#F8E08E"

pluralizeListTitles: false

projectUrls:
    gitHub: "https://github.com/PrestaShop/PrestaShop/"
    reportBug: "https://github.com/PrestaShop/PrestaShop/issues"
    slack: "https://github.com/PrestaShop/open-source/blob/master/content/slack/_index.md"

devdocs: "https://devdocs.prestashop-project.org"

privacy:
    googleAnalytics:
        defaultGtagStorageDenied: true
        waitForUpdate: 500
        googleAnalyticsId: "GTM-MJ8XZ68L"

cookies:
    enable: true

favicon: images/favicon.svg
